#!/usr/bin/python

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Author: Mariano Simone (marianosimone@gmail.com)
# Version: 1.0
# Name: epub-thumbnailer
# Description: An implementation of a cover thumbnailer for epub files
# Installation: see README

import zipfile
import sys
import Image
import os

# Which file are we working with?
input_file = sys.argv[1]
# Where do does the file have to be saved?
output_file = sys.argv[2]
# Required size?
size = int(sys.argv[3])

# Just some examples of what I found inside my epubs...
possible_cover_files = ["cover.png", "cover.jpg", "cover.jpeg"]

# An epub is just a zip
epub_file = zipfile.ZipFile(input_file, "r")

try:
    for fileinfo in epub_file.filelist:
        cover_file = None
        if os.path.basename(fileinfo.filename).lower() in possible_cover_files:
            cover_file = fileinfo
            break
    epub_file.extract(cover_file, "/tmp")
    tmp_cover_path = os.path.join("/tmp", cover_file.filename)
    im = Image.open(tmp_cover_path)
    im.thumbnail((size, size), Image.ANTIALIAS)
    im.save(output_file, "PNG")
    os.remove(tmp_cover_path)
    exit(0)
except Exception as ex:
    print "Couldn't make thumbnail using: ", epub_file.filename, ex

exit(1)
